# This is a basic workflow to help you get started with Actions

name: Website Backend workflow

on:
  push:
    paths:
    - 'backend/**'

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
      - 
        name: Run a one-line script
        uses: actions/checkout@v2
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      -
        name: Installing dependencies from Web API (Django App)
        run: cd backend/ && python -m pip install --upgrade pip && python -m pip install -r requirements.txt
            
      -
        name: Running Unit Tests from Web API (Django App)
        run: cd backend/ && coverage run --source='.' --omit='./*/apps.py,./*/__init__.py,sucre_backend/*,manage.py'  manage.py test && coverage report

