# This is a basic workflow that is manually triggered

name: Website Frontend workflow

on:
  push:
    paths:
    - 'frontend/**'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      -
        name: Run a one-line script
        uses: actions/checkout@v2
      -
        name: Install React Dependencies
        run: cd frontend/ && yarn install

      -
        name: Check Code with Eslint (SPA)
        run: cd frontend/ && yarn lint

      -
        name: Check Code with Prettier (SPA)
        run: cd frontend/ && yarn prettier

      -
        name: Run React Unit Test (SPA)
        run: cd frontend/ && yarn test --coverage --watchAll=false
      -
        name: Build React application (SPA)
        run: cd frontend/ && yarn build

